stylist/urls.py
from django.urls import path

from stylist import views

app_name = "stylist"

urlpatterns = [
    path("", views.StylistIndexView.as_view(), name="stylist-index"),
    path("style/<uuid:uuid>/edit/", views.StylistUpdateView.as_view(), name="stylist-edit"),
    path("style/<uuid:uuid>/preview/", views.StylistPreviewView.as_view(), name="stylist-preview"),
    path("style/<uuid:uuid>/delete/", views.StylistDeleteView.as_view(), name="stylist-delete"),
    path("style/active/", views.StylistActiveView.as_view(), name="stylist-make-active"),
    path("style/preview/end/", views.end_preview, name="stylist-end-preview"),
]

stylist/templates/stylist/active_form.html
{% load crispy_forms_tags %}

<div class="card">
    <div class="p-3 border-bottom d-flex justify-content-between">
        <div class="font-weight-bold mb-0">Change Active Theme</div>
    </div>
    <div class="p-3">
	<p class="text-danger"> Changing the active theme will change the appearance of the site for all users. </p>
	<p> Active Theme: <b>{{ active_theme.name }}</b> </p>
	    
	<form method="POST" action="{% url 'stylist:stylist-make-active' %}">
	    {% csrf_token %}
	    {{ form|crispy }}
	    <input type="submit" value="Change Theme" class="btn btn-primary text-light float-right"></input>
	    <input type="button" name="cancel" value="Cancel" class="btn text-primary font-weight-bold float-right" id="button-id-cancel" data-dismiss="modal">
	</form>
    </div>
</div>

stylist/templates/stylist/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <link rel="shortcut icon" href="/static/favicon.ico"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <title>{% block title %}Stylist{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    {% if preview_style %}
    <link href="{{ preview_style }}" rel="stylesheet" type="text/css">
    {% elif custom_style %}
    <link href="{{ custom_style }}" rel="stylesheet" type="text/css">
    {% else %}
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css">
    {% endif %}
    {% block extra_css %}{% endblock %}
    
    {% block extra_head_js %}{% endblock %}

  </head>
  <body>

    {% if preview_style %}
    <div class="bg-danger text-light container-fluid p-3">
      <div class="row align-items-center">
        <div class="col">
          Theme Preview
        </div>
        <div class="col text-center">
          <b>Refresh to see changes</b>
        </div>
        <div class="col text-right">
          <a href="{% url 'stylist:stylist-end-preview' %}" class="text-light"><b>Cancel Preview</b></a>
        </div>
      </div>
    </div>
    {% endif %}
    
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Stylist</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="/">Home</a>
      </nav>
      <a class="btn btn-outline-primary" href="#">Sign up</a>
    </header>

  <div class="container">
    
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-dismissible {% if message.tags %} alert-{{ message.tags }}{% endif %}">
        <a class="close" data-dismiss="alert">×</a>
        {{ message }}
      </div>
      {% endfor %}
    {% endif %}
    

    {% block content %}
    Stylist Base HTML Template
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
      <div class="row">
        <div class="col-12 col-md">
          <img class="mb-2" src="https://getbootstrap.com/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
          <small class="d-block mb-3 text-muted">© 2020</small>
        </div>
        <div class="col-6 col-md">
          <h5>Features</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Cool stuff</a></li>
            <li><a class="text-muted" href="#">Random feature</a></li>
            <li><a class="text-muted" href="#">Team feature</a></li>
            <li><a class="text-muted" href="#">Stuff for developers</a></li>
            <li><a class="text-muted" href="#">Another one</a></li>
            <li><a class="text-muted" href="#">Last time</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Resource</a></li>
            <li><a class="text-muted" href="#">Resource name</a></li>
            <li><a class="text-muted" href="#">Another resource</a></li>
            <li><a class="text-muted" href="#">Final resource</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Team</a></li>
            <li><a class="text-muted" href="#">Locations</a></li>
            <li><a class="text-muted" href="#">Privacy</a></li>
            <li><a class="text-muted" href="#">Terms</a></li>
          </ul>
        </div>
      </div>
    </footer>
  </div>

  <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  <script>
  setTimeout(function () {
      $(".alert").slideUp(500);
  }, 3000);
  </script>

  {% block extra_js %}{% endblock %}
  </body>
</html>

stylist/templates/stylist/index.html
{% extends "stylist/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Stylist - Home{% endblock %}

{% block content %}
<div class="container">
    <div class="row mb-4 align-items-center">
        <div class="col">
            <h1> Themes </h1>
        </div>
        <div class="col text-right">
            Active Theme: <b> {{ active_theme.name }} </b>
            <a class="btn btn-primary text-light ml-2" data-toggle="modal" data-target="#form_modal" href="{% url 'stylist:stylist-make-active' %}"> Change </a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h3>Available Themes</h3>
            <p> Edit, preview, and create new design themes for your site. </p>
            <ul>
                {% for style in object_list %}
                <li>
                    <a href="{{style.get_absolute_url}}">Edit {{ style.name }}</a>
                    <ul>
                        <li>
                            <a href="{% url 'stylist:stylist-delete' style.uuid %}" data-toggle="modal" data-target="#form_modal"> Delete </a>
                        </li>
                        <li>
                            <form method="POST" id="preview-form-{{style.id}}" action="{% url 'stylist:stylist-preview' style.uuid %}" target="_blank">
                                {% csrf_token %}
                                <input type="hidden" name="name" value="{{style.name}}">
                                {% for key, value in style.attrs.items %}
                                <input type="hidden" name="{{key}}" value="{{value}}">
                                {% endfor %}
                                <a href="#" onClick="document.getElementById('preview-form-{{style.id}}').submit();"> Preview </a>
                            </form>
                        </li>
                        <li>
                            <form method="POST" id="duplicate-form-{{style.id}}" action="{% url 'api-duplicate-style' style.uuid %}">
                                {% csrf_token %}
                                {{ form.name.as_hidden }}
                                {{ form.enabled.as_hidden }}
                                <a href="#" onClick="document.getElementById('duplicate-form-{{style.id}}').submit();"> Duplicate </a>
                            </form>
                        </li>
                    </ul>
                </li>
                {% endfor %}
            </ul>

            <form method="POST" action="{% url 'api-create-style' %}">
                {% csrf_token %}
                {{ form.name.as_hidden }}
                {{ form.enabled.as_hidden }}
                <input type="submit" value="New Theme" class="btn btn-primary text-light"></input>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="form_modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
	    
        </div>
    </div>
</div>


{% endblock %}


{% block extra_js %}
<script>
    $(document).ready(function() {

        $('#form_modal').on('show.bs.modal', function (evt) {
            var modal = $(this).find('.modal-content');
            var url = evt.relatedTarget.href; {% comment %}// pull form contents from href attr of button{% endcomment %}
            $.ajax({
                url: url,
                context: document.body
            }).done(function(response) {
                modal.html(response);
            });
        });

    });
</script>
{% endblock %}

stylist/templates/stylist/style_delete.html
{% load crispy_forms_tags %}

<div class="card">
    <div class="p-3 border-bottom d-flex justify-content-between">
        <div class="font-weight-bold mb-0">Delete Theme</div>
    </div>
    <div class="p-3">
	<p>
	    You are about to permanently delete the following theme: <b>{{ object.name }}</b>
	</p>
	    
	<form method="POST" action="{% url 'stylist:stylist-delete' uuid=object.uuid %}">
	    {% csrf_token %}
	    <input type="submit" value="Permanently Delete" class="btn btn-primary text-light float-right"></input>
	    <input type="button" name="cancel" value="Cancel" class="btn text-primary font-weight-bold float-right" id="button-id-cancel" data-dismiss="modal">
	</form>
    </div>
</div>

stylist/templates/stylist/style_form.html
{% extends "stylist/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Stylist - Home{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
	<div class="col">
	    <h1>Edit {{ object.name }}</h1>
	</div>
	<div class="col text-right">
	    <a id="preview" class="btn text-primary"> Preview </a>
	    <a href="{% url 'stylist:stylist-index' %}" class="btn text-primary"> Exit </a>
	</div>
    </div>
    <div class="row">

	<form method="POST" id="style_form">
	    {% csrf_token %}
	    {{ form|crispy }}
	    <input type="submit" value="Update" class="btn btn-primary text-light my-3">
	</form>
    </div>
</div>

{% endblock %}

{% block extra_js %}
<script>
    $( document ).ready(function() {
      var form = document.getElementById("style_form");

      document.getElementById("preview").addEventListener("click", function () {
        form.action = "{% url 'stylist:stylist-preview' uuid=object.uuid %}";
        form.target = "_blank";
        form.submit();
        $(form).removeAttr("action");
        $(form).removeAttr("target");
      });
    });
</script>
{% endblock %}